In [1]:
import sys
sys.path.insert(0,'..')


import sys
import numpy as np
import time_evolving_mpo as tempo


Omega = 1.0
omega_cutoff = 3.0
alpha = 0.1
temperature = 0.0
start_time = 0.0
end_time = 1.0
initial_state = tempo.operators.spin_dm("y+")

def generate_process_tensor():


    correlations = tempo.PowerLawSD(alpha=alpha,
                                    zeta=3,
                                    cutoff=omega_cutoff,
                                    cutoff_type='exponential',
                                    temperature=temperature)
    bath = tempo.Bath(0.5 * tempo.operators.sigma("z"), correlations)

    dt = 0.1 # 0.01
    dkmax = 20 # 200
    epsrel = 1.0e-6# 1.0e-7

    pt_tempo_parameters = tempo.PtTempoParameters(dt=dt, dkmax=dkmax, epsrel=epsrel)
    pt = tempo.pt_tempo_compute(bath=bath,
                                start_time=start_time,
                                end_time=end_time,
                                parameters=pt_tempo_parameters,
                                progress_type='bar')
    pt.export("details_pt_tempo.processTensor",overwrite=True)

generate_process_tensor()




100.0%   10 of   10 [########################################] 00:00:00
Elapsed time: 0.1s


In [2]:
pt = tempo.import_adjoint_process_tensor('details_pt_tempo.processTensor','adjoint')
system = tempo.System(0.0 * tempo.operators.sigma("x"))
output_states = pt.compute_derivatives_from_system(system,initial_state=np.array([[1,0],[0,0]]),target_state = np.array([[0,0],[0,1]]))



0
1
2
3
4
5
6
7
8
9
[Node
(
name : '__unnamed_node__',
tensor : 
array([[1, 0, 0, 0]]),
edges : 
[
Edge(Dangling Edge)[0] 
, 
Edge(Dangling Edge)[1] 
] 
), Node
(
name : '__unnamed_node__',
tensor : 
array([[ 1.57404578+9.62636075e-02j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
       [ 0.61236506+2.91521103e-01j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
       [-1.0217538 +3.09331126e-21j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
       [-0.08586847-4.22309603e-02j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j]]),
edges : 
[
Edge(Dangling Edge)[0] 
, 
Edge(Dangling Edge)[1] 
] 
), Node
(
name : '__unnamed_node__',
tensor : 
array([[ 1.57404578+9.62636075e-02j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
       [ 0.61236506+2

In [6]:
pt.backwards

[Node
 (
 name : 'current',
 tensor : 
 array([[0, 0, 0, 1]]),
 edges : 
 [
 Edge(Dangling Edge)[0] 
 , 
 Edge(Dangling Edge)[1] 
 ] 
 ),
 Node
 (
 name : '__unnamed_node__',
 tensor : 
 array([[ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j, -2.05645869e-05+2.00400398e-04j],
        [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j, -8.18342100e-01+1.69936850e-19j],
        [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j, -1.41016945e-03-2.01452778e-04j]]),
 edges : 
 [
 Edge(Dangling Edge)[0] 
 , 
 Edge(Dangling Edge)[1] 
 ] 
 ),
 Node
 (
 name : '__unnamed_node__',
 tensor : 
 array([[ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          0.00000000e+00+0.00000000e+00j, -2.05645869e-05+2.00400398e-04j],
        [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          

In [38]:
[pt.forwards[i].tensor.shape for i in range(9)]

[(1, 4), (4, 4), (4, 4), (15, 4), (15, 4), (27, 4), (27, 4), (27, 4), (27, 4)]

In [39]:

[pt.backwards[i].tensor.shape for i in range(9)]

[(1, 4), (3, 4), (3, 4), (9, 4), (9, 4), (16, 4), (16, 4), (22, 4), (22, 4)]